# 错误处理与测试

defer-panic-and-recover



Go 有一个预先定义的 error 接口类型

```go
type error interface {
	Error() string
}
```

```go
err := errors.New("math - square root of negative number")
```



发生错误必须中止程序时，`panic()` 可以用于错误处理模式

>Go panicking：
>
>在多层嵌套的函数调用中调用 `panic()`，可以马上中止当前函数的执行，所有的 `defer` 语句都会保证执行并把控制权交还给接收到 panic 的函数调用者。这样向上冒泡直到最顶层，并执行（每层的） `defer`，在栈顶处程序崩溃，并在命令行中用传给 `panic()` 的值报告错误情况：这个终止过程就是 *panicking*。
>
>标准库中有许多包含 `Must` 前缀的函数，像 `regexp.MustComplie()` 和 `template.Must()`；当正则表达式或模板中转入的转换字符串导致错误时，这些函数会 `panic()`。
>
>不能随意地用 `panic()` 中止程序，必须尽力补救错误让程序能继续执行。

>正如名字一样，这个 (`recover()`) 内建函数被用于从 panic 或错误场景中恢复：让程序可以从 panicking 重新获得控制权，停止终止过程进而恢复正常执行。
>
>`recover` 只能在 `defer` 修饰的函数（参见 [6.4 节](https://gitee.com/wangjie2020/the-way-to-go_ZH_CN/blob/master/eBook/06.4.md)）中使用：用于取得 `panic()` 调用中传递过来的错误值，如果是正常执行，调用 `recover()` 会返回 `nil`，且没有其它效果。
>
>总结：`panic()` 会导致栈被展开直到 `defer` 修饰的 `recover()` 被调用或者程序中止。



